# playbook.yml
- name: Setup Dev Environment on Hetzner Server
  hosts: all
  become: true

  vars:
    dotfiles_repo: "https://github.com/alexbenisch/dotfiles.git"
    lazyvim_repo: "https://github.com/LazyVim/starter.git"
    user: alex
    home: "/home/alex"

  tasks:
    - name: Ensure packages are installed
      package:
        name:
          - zsh
          - git
          - tmux
          - stow
          - gnupg
          - curl
          - ripgrep
          - fd-find
          - neovim
          - lua
          - make
          - gcc
        state: present

    - name: Clone dotfiles repo
      git:
        repo: "{{ dotfiles_repo }}"
        dest: "{{ home }}/dotfiles"
        version: HEAD
        update: no
      become_user: "{{ user }}"

    - name: Clone LazyVim starter
      git:
        repo: "{{ lazyvim_repo }}"
        dest: "{{ home }}/.config/nvim"
        version: HEAD
        update: no
      become_user: "{{ user }}"

    - name: Symlink dotfiles
      shell: stow -d {{ home }}/dotfiles -t {{ home }} zsh tmux nvim
      args:
        chdir: "{{ home }}/dotfiles"
      become_user: "{{ user }}"

    - name: Run Neovim to install plugins
      shell: nvim --headless "+Lazy sync" +qa
      become_user: "{{ user }}"
